import type { ChainConfig, ChainId } from "./types";

export const CHAIN_CONFIGS: Record<ChainId, ChainConfig> = {
  solana: {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    icon: "◎",
    color: "hsl(var(--terminal-green))",
    decimals: 9,
    explorerUrl: "https://solscan.io",
    explorerAddressPath: "/account/",
    explorerTxPath: "/tx/",
    isCompliance: false,
    status: "active",
    capabilities: { supportsTokens: true, supportsTransfers: true, supportsHistory: true, supportsComplianceView: false },
  },
  bitcoin: {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    icon: "₿",
    color: "hsl(38, 92%, 50%)",
    decimals: 8,
    explorerUrl: "https://mempool.space",
    explorerAddressPath: "/address/",
    explorerTxPath: "/tx/",
    isCompliance: true,
    status: "active",
    capabilities: { supportsTokens: false, supportsTransfers: true, supportsHistory: true, supportsComplianceView: true },
  },
  ethereum: {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    icon: "Ξ",
    color: "hsl(228, 65%, 60%)",
    decimals: 18,
    explorerUrl: "https://etherscan.io",
    explorerAddressPath: "/address/",
    explorerTxPath: "/tx/",
    isCompliance: false,
    status: "active",
    capabilities: { supportsTokens: true, supportsTransfers: true, supportsHistory: true, supportsComplianceView: true },
  },
  xrpl: {
    id: "xrpl",
    name: "XRP Ledger",
    symbol: "XRP",
    icon: "✕",
    color: "hsl(var(--terminal-blue))",
    decimals: 6,
    explorerUrl: "https://xrpscan.com",
    explorerAddressPath: "/account/",
    explorerTxPath: "/tx/",
    isCompliance: true,
    status: "active",
    capabilities: { supportsTokens: true, supportsTransfers: true, supportsHistory: true, supportsComplianceView: true },
  },
  stellar: {
    id: "stellar",
    name: "Stellar",
    symbol: "XLM",
    icon: "✦",
    color: "hsl(var(--terminal-cyan))",
    decimals: 7,
    explorerUrl: "https://stellar.expert",
    explorerAddressPath: "/explorer/public/account/",
    explorerTxPath: "/explorer/public/tx/",
    isCompliance: true,
    status: "active",
    capabilities: { supportsTokens: true, supportsTransfers: true, supportsHistory: true, supportsComplianceView: true },
  },
  quant: {
    id: "quant",
    name: "Quant",
    symbol: "QNT",
    icon: "◆",
    color: "hsl(263, 60%, 55%)",
    decimals: 18,
    explorerUrl: "https://etherscan.io/token/0x4a220E6096B25EADb88358cb44068A3248254675",
    explorerAddressPath: "/address/",
    explorerTxPath: "/tx/",
    isCompliance: true,
    status: "active",
    capabilities: { supportsTokens: false, supportsTransfers: false, supportsHistory: false, supportsComplianceView: true },
  },
  xdc: {
    id: "xdc",
    name: "XDC Network",
    symbol: "XDC",
    icon: "⬡",
    color: "hsl(200, 70%, 50%)",
    decimals: 18,
    explorerUrl: "https://xdcscan.io",
    explorerAddressPath: "/address/",
    explorerTxPath: "/tx/",
    isCompliance: true,
    status: "active",
    capabilities: { supportsTokens: true, supportsTransfers: true, supportsHistory: false, supportsComplianceView: true },
  },
  hedera: {
    id: "hedera",
    name: "Hedera",
    symbol: "HBAR",
    icon: "ℏ",
    color: "hsl(260, 55%, 55%)",
    decimals: 8,
    explorerUrl: "https://hashscan.io/mainnet",
    explorerAddressPath: "/account/",
    explorerTxPath: "/transaction/",
    isCompliance: true,
    status: "active",
    capabilities: { supportsTokens: true, supportsTransfers: true, supportsHistory: false, supportsComplianceView: true },
  },
  algorand: {
    id: "algorand",
    name: "Algorand",
    symbol: "ALGO",
    icon: "Ⱥ",
    color: "hsl(0, 0%, 85%)",
    decimals: 6,
    explorerUrl: "https://allo.info",
    explorerAddressPath: "/account/",
    explorerTxPath: "/tx/group/",
    isCompliance: true,
    status: "active",
    capabilities: { supportsTokens: true, supportsTransfers: true, supportsHistory: false, supportsComplianceView: true },
  },
  iota: {
    id: "iota",
    name: "IOTA",
    symbol: "IOTA",
    icon: "ι",
    color: "hsl(180, 50%, 50%)",
    decimals: 18,
    explorerUrl: "https://explorer.iota.org/mainnet",
    explorerAddressPath: "/addr/",
    explorerTxPath: "/tx/",
    isCompliance: true,
    status: "active",
    capabilities: { supportsTokens: false, supportsTransfers: true, supportsHistory: false, supportsComplianceView: true },
  },
};

export const ACTIVE_CHAINS = Object.values(CHAIN_CONFIGS).filter(c => c.status === "active");
export const COMPLIANCE_CHAINS = ACTIVE_CHAINS.filter(c => c.isCompliance);

export function getChainConfig(chainId: ChainId): ChainConfig {
  return CHAIN_CONFIGS[chainId];
}
