import { Check, X, Zap, Crown, Rocket } from "lucide-react";
import { Link } from "react-router-dom";

const TIERS = [
  { name: "FREE", price: "$0", period: "forever", icon: Zap, color: "border-muted-foreground/30", badgeColor: "bg-muted text-muted-foreground", cta: null, features: [{ label: "Basic signals", included: true }, { label: "1 tracked wallet", included: true }, { label: "3 alerts", included: true }, { label: "Sniper Mode", included: false }, { label: "Smart Money Tracker", included: false }, { label: "Copy Trading", included: false }, { label: "Auto Sniper", included: false }] },
  { name: "PRO", price: "$29", period: "/month", icon: Crown, color: "border-terminal-cyan/50", badgeColor: "bg-terminal-cyan/10 text-terminal-cyan", cta: "#pro-checkout", popular: true, features: [{ label: "Basic signals", included: true }, { label: "5 tracked wallets", included: true }, { label: "20 alerts", included: true }, { label: "Sniper Mode", included: true }, { label: "Smart Money Tracker", included: true }, { label: "Copy Trading", included: false }, { label: "Auto Sniper", included: false }] },
  { name: "ELITE", price: "$99", period: "/month", icon: Rocket, color: "border-terminal-yellow/50", badgeColor: "bg-terminal-yellow/10 text-terminal-yellow", cta: "#elite-checkout", features: [{ label: "Basic signals", included: true }, { label: "Unlimited wallets", included: true }, { label: "Unlimited alerts", included: true }, { label: "Sniper Mode", included: true }, { label: "Smart Money Tracker", included: true }, { label: "Copy Trading", included: true }, { label: "Auto Sniper", included: true }] },
];

export default function Pricing() {
  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <div className="text-center space-y-3 pt-2"><h1 className="text-2xl md:text-3xl font-mono font-bold text-foreground">Stop Missing <span className="text-primary">Alpha</span></h1><p className="text-sm font-mono text-muted-foreground max-w-md mx-auto">Every minute without Pro, you're watching others profit.<br />Upgrade now. Cancel anytime.</p></div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{TIERS.map((tier) => { const Icon = tier.icon; return (<div key={tier.name} className={`relative rounded-lg border ${tier.color} bg-card p-5 flex flex-col ${tier.popular ? "ring-1 ring-terminal-cyan/30" : ""}`}>{tier.popular && <div className="absolute -top-2.5 left-1/2 -translate-x-1/2 px-3 py-0.5 rounded-full bg-terminal-cyan/20 text-terminal-cyan text-[9px] font-mono font-bold border border-terminal-cyan/30">MOST POPULAR</div>}<div className="flex items-center gap-2 mb-4"><div className={`p-1.5 rounded ${tier.badgeColor}`}><Icon className="h-4 w-4" /></div><span className="font-mono font-bold text-sm text-foreground">{tier.name}</span></div><div className="mb-5"><span className="text-3xl font-mono font-black text-foreground">{tier.price}</span><span className="text-xs font-mono text-muted-foreground ml-1">{tier.period}</span></div><ul className="space-y-2.5 flex-1 mb-6">{tier.features.map((f) => (<li key={f.label} className="flex items-center gap-2 text-xs font-mono">{f.included ? <Check className="h-3.5 w-3.5 text-terminal-green flex-shrink-0" /> : <X className="h-3.5 w-3.5 text-muted-foreground/40 flex-shrink-0" />}<span className={f.included ? "text-foreground" : "text-muted-foreground/50 line-through"}>{f.label}</span></li>))}</ul>{tier.cta ? <a href={tier.cta} className={`block text-center py-2.5 rounded-md text-xs font-mono font-bold transition-colors ${tier.popular ? "bg-terminal-cyan text-background hover:bg-terminal-cyan/80" : "bg-terminal-yellow text-background hover:bg-terminal-yellow/80"}`}>Get {tier.name}</a> : <Link to="/" className="block text-center py-2.5 rounded-md text-xs font-mono font-bold border border-border text-muted-foreground hover:bg-muted transition-colors">Current Plan</Link>}</div>); })}</div>
      <p className="text-center text-[10px] font-mono text-muted-foreground pb-4">Cancel anytime · No lock-in · Instant access after payment</p>
    </div>
  );
}