// This file is auto-generated by Lovable. Do not modify it.
// NOTE: Tanner Terminal uses wallet-only authentication.
// Google/Apple OAuth is disabled for this project.
// The lovable.auth.signInWithOAuth method is a no-op that returns an error.

export const lovable = {
  auth: {
    signInWithOAuth: async (_provider: "google" | "apple") => {
      console.warn("[lovable] signInWithOAuth is disabled — Tanner Terminal uses wallet auth only");
      return { error: new Error("OAuth is disabled. Use wallet authentication.") };
    },
  },
};
